name: SkyWarsReloaded
main: com.walrusone.skywars.SkyWarsReloaded
version: 2.8

depend: [Vault]
softdepend: [Multiverse-Core]

commands:
   swr:
      description: This is the main plugin command.
      aliases: [sw]
      usage: /<command> [args]
   global:
      aliases: [g]
      description: Allows you to send a message to all players
permissions:
  swr.*:
    description: Gives access to all swr commands
    children:
      swr.play: true
      swr.maps: true
      swr.signs: true
      swr.spectate: true
      swr.start: true
  swr.play:
    description: Gives access to the swr join and quit commands
    default: true
    children:
      swr.join: true
      swr.quit: true
      swr.kit: true
      swr.stats: true
  swr.admin:
    description: Gives access to the swr setspawn, list, games, endgame, and reload commands
    default: op
    children:
      swr.setspawn: true
      swr.list: true
      swr.games: true
      swr.endgame: true
      swr.reload: true
      swr.addpoints: true
      swr.removepoints: true
      swr.setglass: true
      swr.seteffect: true
      swr.setprojeffect: true
  swr.maps: 
    description: Allows a player to use map commands.
    default: op
    children:
      swr.create: true
      swr.delete: true
      swr.edit: true
      swr.list: true
      swr.save: true
      swr.register: true
      swr.unregister: true
  swr.signs:
    description: Allows the user to create and destory swr signs.
    default: op
  swr.spectate:    
    description: Allows the user to spectate games.
    default: op
  swr.spectateshop:    
    description: Allows the user to use the spectator shop.
    default: op
  swr.opchest:    
    description: Allows the user to vote for OP chests.
    default: op
  swr.timevote:    
    description: Allows the user to vote for time of day on game start.
    default: op
  swr.jumpvote:    
    description: Allows the user to vote for jump boost on game start.
    default: op
  swr.start: 
    description: Allows the user to force start a game.
    default: op
  swr.global: 
    description: Allows the user to use global chat.
    default: op
  swr.vip:
    description: When a player has this permission, their score for kills and wins is given the vip multiplier in the config.
    default: op
  swr.color:
    description: Allows a player to use color chat.
    default: op
  swr.colorshop:
    description: Allows a player to use the color glass shop.
    defualt: op
  swr.permkits:
    description: Allows a player to use the permanent kits shop.
    default: op
  swr.join: 
    description: Allows a player to join a game.
    default: true
  swr.quit: 
    description: Allows a player to quit a game.
    default: true
  swr.kit: 
    description: Allows a player to use the kit menu item.
    default: true
  swr.stats: 
    description: Allows a player to use the swrstats command.
    default: true
  swr.setspawn: 
    description: Allows a player to use the setspawn command.
    default: op
  swr.games: 
    description: Allows a player to use the games command.
    default: op
  swr.list: 
    description: Aloows a player to use the list command.
    default: op
  swr.endgame: 
    description: Allows a player to use the endgame command.
    default: op
  swr.reload: 
    description: Allows a player to use the reload command.
    default: op
  swr.create: 
    description: Allows a player to use the create command.
    default: op
  swr.delete: 
    description: Allows a player to use the delete command.
    default: op
  swr.register: 
    description: Allows a player to use the register command.
    default: op
  swr.unregister: 
    description: Allows a player to use the unregister command.
    default: op
  swr.save: 
    description: Allows a player to use the save command.
    default: op
  swr.edit: 
    description: Allows a player to use the edit command.
    default: op
  swr.addpoints: 
    description: Allows a player to use the addpoints command.
    default: op
  swr.removepoints: 
    description: Allows a player to use the removepoints command.
    default: op
  swr.setglass: 
    description: Allows a player to use the setglass command.
    default: op
  swr.seteffect: 
    description: Allows a player to use the seteffect command.
    default: op
  swr.setprojeffect: 
    description: Allows a player to use the setprojeffect command.
    default: op